### ISSUE TITLE
Error: ENOENT: no such file or directory - Caused by question marks in Windows files

### ISSUE THREAD

**Issue by Ty-Grr** [mapleweekend/easy-reddit-downloader#7] opened 2022-12-24 10:00 UTC
ran npm i and then when running the program, I receive error that it cannot open the logs file. 

```
Welcome to Reddit Post Downloader!
Contribute @ https://github.com/mapleweekend/easy-reddit-downloader
What subreddit would you like to download?You may submit multiple separated by commas (no spaces).
         D:\Apps\easy-reddit-downloader\index.js:446
                if (err) throw err;
                         ^

[Error: ENOENT: no such file or directory, open 'D:\Apps\easy-reddit-downloader\logs\2022 11 24
  at
  9-57-45.txt'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'D:\\Apps\\easy-reddit-downloader\\logs\\2022 11 24 \n  at \n  9-57-45.txt'
}
```

https://i.imgur.com/oLFcI2h.png

**Comment by mapleweekend** [comment] 2022-12-24 14:04
Can you try creating a "logs" folder at the parent directory?On Dec 24, 2022 5:00 AM, Ty-Grr ***@***.***> wrote:
ran npm i and then when running the program, I receive error that it cannot open the logs file.
Welcome to Reddit Post Downloader!
Contribute @ https://github.com/mapleweekend/easy-reddit-downloader
What subreddit would you like to download?You may submit multiple separated by commas (no spaces).
         D:\Apps\easy-reddit-downloader\index.js:446
                if (err) throw err;
                         ^

[Error: ENOENT: no such file or directory, open 'D:\Apps\easy-reddit-downloader\logs\2022 11 24
  at
  9-57-45.txt'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'D:\\Apps\\easy-reddit-downloader\\logs\\2022 11 24 \n  at \n  9-57-45.txt'
}

https://i.imgur.com/oLFcI2h.png

**Comment by mapleweekend** [comment] 2022-12-24 14:39
Hi @Ty-Grr! I just pushed a new commit that just creates the "logs" folder at the repo level. I then cloned the repo myself and tried it. Seems like it works. 

<img width="566" alt="Screenshot 2022-12-24 at 9 35 42 AM" src="https://user-images.githubusercontent.com/73198556/209440435-aee6b6de-0e72-442f-ab1c-8aa64eb39b3d.png">

Can you see if pulling the latest fixes it (or simply creating the "logs" folder at the repo level)?

**Comment by Ty-Grr** [comment] 2022-12-24 16:23
Same error, the logs folder was already created in the directory before the new update 

I'd even tried to create the folder 2022 11 24.

Cloned the repo and even downloaded the zip for it.

https://i.imgur.com/9aJvdw9.png

**Comment by mapleweekend** [comment] 2022-12-24 16:39
@Ty-Grr Thanks for that screenshot. I wonder if this could be caused by an incorrectly-placed newline in the date formatting. Do you mind cloning again and trying? I took out the newline in the date format string

**Comment by Ty-Grr** [comment] 2022-12-24 18:53
that worked to then start and download but one of the text files through an error

I blurred due to what type of text file was trying to download but it did contain a special characters (question mark)

https://i.imgur.com/Fkj3zP3.png

not sure if anything in place to replace these characters in the title.

**Comment by mapleweekend** [comment] 2022-12-24 19:25
@Ty-Grr Oh, weird. MacOS doesn't mind the question mark in the title, but it seems that Windows does. 

I will write a fix right now that removes the question mark. Do you have a preferred character to replace it with, or should I just remove the question mark?

**Comment by Ty-Grr** [comment] 2022-12-24 19:30
Removing it would probably be easiest. 
May want to replace all the other blocked windows characters in file names aswell.

**Comment by mapleweekend** [comment] 2022-12-24 19:39
https://github.com/mapleweekend/easy-reddit-downloader/pull/12 Just merged this PR that has a new sanitizer function for respecting file name chars on Mac, Windows, and Linux! 

Tested and working on Mac and Windows with a few different subreddits. Should work fine! 

Can you please validate that this fixed it for ya? 

```
function sanitizeFileName(fileName) {
	return fileName.replace(/[/\\?%*:|"<>]/g, '-').substring(0,200);
}
```

**Comment by Ty-Grr** [comment] 2022-12-24 19:44
Yes that worked but the application stopped at 102 posts. set to 1000 posts, hot > all > every day 

https://i.imgur.com/1Qmbqhy.png

**Comment by mapleweekend** [comment] 2022-12-24 19:45
Let's move that to this separate issue! #8 

I'll have to add pagination which I should be able to do either later tonight, or possibly tomorrow! Shouldn't be too hard, just a busy day! 😄

**Closed by mapleweekend** 2022-12-24 19:45 UTC
Labels: bug

**Comment by mapleweekend** [comment] 2022-12-25 03:15
@Ty-Grr Just completed the issue mentioned above so you can now download more than 100 posts per sub per query! 🎉
